In [1]:
import numpy as np 

In [2]:
X=np.array([[1,1,1,1],[0,0.5,0,0],[0,0,0,0],[1,1,0.5,1],[0,0,0,0]])

In [3]:
X

array([[1. , 1. , 1. , 1. ],
       [0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [1. , 1. , 0.5, 1. ],
       [0. , 0. , 0. , 0. ]])

In [4]:
[u,s,vt]=np.linalg.svd(X)

In [10]:
s

array([2.68637317, 0.44069543, 0.29864147, 0.        ])

In [6]:
u1=u[:,0].reshape(5,1)
v1=vt[0,:].reshape(1,4)
u2=u[:,1].reshape(5,1)
v2=vt[1,:].reshape(1,4)
u3=u[:,2].reshape(5,1)
v3=vt[2,:].reshape(1,4)

In [7]:
v1

array([[-0.52302548, -0.54179451, -0.39918343, -0.52302548]])

In [8]:
u1.dot(v1)*s[0] + u2.dot(v2)*s[1]  + u3.dot(v3)*s[2] 

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [ 1.17961196e-16,  5.00000000e-01,  8.32667268e-17,
        -7.63278329e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  5.00000000e-01,
         1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])