In [1]:
pip install control

     |████████████████████████████████| 348kB 4.0MB/s 
  Created wheel for control: filename=control-0.9.0-py2.py3-none-any.whl size=344920 sha256=4e324dde936c1a1dc6bcd64456c792004af79548c0fd4f60024e018ea787fb9d
  Stored in directory: /root/.cache/pip/wheels/35/be/ee/081b68ca3e4b2d253fba2f7f7e51960373903fb7b6d13c5532
Successfully built control


In [2]:
pip install slycot

     |████████████████████████████████| 1.6MB 3.8MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for slycot: filename=slycot-0.4.0-cp37-cp37m-linux_x86_64.whl size=1417832 sha256=ae332432f44849425c084839116035bc278b2c16830f4c4002e8496892063ff5
  Stored in directory: /root/.cache/pip/wheels/a2/46/56/f82cbb2fd06556f4f3952a2eb2396e8fd29264fffecbaad3cf
Successfully built slycot


In [3]:
import numpy as np
from control.matlab import *
import slycot

In [7]:
A = np.array([[-1,0],[0,-2]])
B = np.array([0.01,1]).reshape(2,1)
C = np.array([0.01,1])
D = 0

sys = ss(A,B,C,D)

Wc = gram(sys,'c') # Controllability Gramian
Wo = gram(sys,'o') # Observability Gramian

In [8]:
c=ctrb(A,B)
o=obsv(A,C)

matrix([[5.00000000e-05, 3.33333333e-03],
        [3.33333333e-03, 2.50000000e-01]])

In [16]:
c

matrix([[ 0.01, -0.01],
        [ 1.  , -2.  ]])

In [10]:
np.linalg.eigh(Wc)

(array([5.55456805e-06, 2.50044445e-01]), matrix([[-0.99991112,  0.01333244],
         [ 0.01333244,  0.99991112]]))

In [11]:
np.linalg.svd(o)

(matrix([[-0.44722433,  0.89442182],
         [ 0.89442182,  0.44722433]]),
 array([2.23610823, 0.00447206]),
 matrix([[-0.00599992, -0.999982  ],
         [ 0.999982  , -0.00599992]]))